{"uuid": "3c83c0c5-300b-4672-ae4c-05afccede260", "children": ["04902925-780d-4c08-b75e-1ece9406b42a", "1dc4df35-eff9-4624-8cd9-b5ee95ef0f63", "3dc2b4a1-85a7-4817-b70b-9de32d379f28", "b28f514e-20a6-42ad-b021-9d329c90b11a", "e110cb09-a6e2-4720-9c8a-b80102b6d0f5"], "befores": [{"name": "get_job_details", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.expomedics.com', port=443): Max retries exceeded with url: /jobs?country=romania (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7f24f982f550>: Failed to resolve 'www.expomedics.com' ([Errno -3] Temporary failure in name resolution)\"))\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/tests/Test_API_Suite/test_expomedics.py\", line 14, in get_job_details\n    scraper_data = expomedicsScraper().return_data()\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/sites/expomedics.py\", line 53, in return_data\n    self.get_response()\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/sites/expomedics.py\", line 25, in get_response\n    self.get_content(self.url)\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/sites/website_scraper_bs4.py\", line 34, in get_content\n    response = requests.get(url, headers=self.DEFAULT_HEADERS, verify=False)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/api.py\", line 73, in get\n    return request(\"get\", url, params=params, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/adapters.py\", line 519, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1707973859143, "stop": 1707973869173}], "start": 1707973859143, "stop": 1707973869735}