{"uuid": "adb3b138-f400-456e-a941-17190fc461bd", "children": ["fdc4613a-0bba-4516-8738-41e09168d376", "27f7ffee-0908-4137-ad14-2ea37f4d8569", "4c222cb8-fd67-4b1a-ad42-a3349c2205bc", "87419208-2ca5-4591-8bcb-d9d005e97c10", "da4b0997-50f8-48e1-ac3b-7b875ea6f085"], "befores": [{"name": "get_job_details", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.expomedics.com', port=443): Max retries exceeded with url: /jobs?country=romania (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7f5707b5c100>: Failed to resolve 'www.expomedics.com' ([Errno -3] Temporary failure in name resolution)\"))\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/tests/Test_API_Suite/test_expomedics.py\", line 14, in get_job_details\n    scraper_data = expomedicsScraper().return_data()\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/sites/expomedics.py\", line 53, in return_data\n    self.get_response()\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/sites/expomedics.py\", line 25, in get_response\n    self.get_content(self.url)\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/sites/website_scraper_bs4.py\", line 34, in get_content\n    response = requests.get(url, headers=self.DEFAULT_HEADERS, verify=False)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/api.py\", line 73, in get\n    return request(\"get\", url, params=params, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/adapters.py\", line 519, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1707382000210, "stop": 1707382010225}], "start": 1707382000210, "stop": 1707382010751}