{"uuid": "bbd2bf99-8f3a-46ef-94b7-772c47f6232f", "children": ["af94dbdd-1843-4026-918d-927e0b4a2a1e", "55b80d27-e572-4224-beb7-b5835e9c4cc5", "14baee66-350f-4857-bd02-ced481a41c5e", "9bd112aa-22aa-4fdd-92c2-d7b73357fa88", "58a4f7b8-d7da-4915-ac4b-1831b4e1eb35"], "befores": [{"name": "get_job_details", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='ellisium.ro', port=443): Max retries exceeded with url: /cariere/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc597e71900>, 'Connection to ellisium.ro timed out. (connect timeout=None)'))\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/tests/Test_API_Suite/test_ellisium.py\", line 14, in get_job_details\n    scraper_data = ellisiumScraper().return_data()\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/sites/ellisium.py\", line 42, in return_data\n    self.get_response()\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/sites/ellisium.py\", line 25, in get_response\n    self.get_content(self.url)\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/sites/website_scraper_bs4.py\", line 34, in get_content\n    response = requests.get(url, headers=self.DEFAULT_HEADERS, verify=False)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/api.py\", line 73, in get\n    return request(\"get\", url, params=params, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/adapters.py\", line 507, in send\n    raise ConnectTimeout(e, request=request)\n"}, "start": 1711476554686, "stop": 1711476685197}], "start": 1711476554686, "stop": 1711476685626}